const sharedCategories = [
  'African',
  'Asian',
  'BBQ',
  'British',
  'Cheese',
  'Chinese',
  'Curry',
  'Ethiopian',
  'French',
  'German',
  'Indian',
  'Indonesian',
  'Italian',
  'Japanese',
  'Korean',
  'Malaysian',
  'Mediterranean',
  'Mexican',
  'Mezze',
  'Middle Eastern',
  'Pakistani',
  'Pasta',
  'Ramen',
  'Salad',
  'Sandwiches',
  'Seafood',
  'Steak',
  'Sushi',
  'Thai',
  'Vegetarian',
  'Vegan',
  'Vietnamese',
  'Swiss'
];

export const foodCategories = [
  ...sharedCategories,
  'Burger',
  'Chicken',
  'Dessert',
  'Meat',
  'Pizza',
  'Rice Dish',
  'Soup'
];

export const restaurantCategories = [
  ...sharedCategories,
  'Burger Shack',
  'Chicken Shop',
  'Pizzeria',
  'Pub',
  'Steakhouse'
];

export const categories = [
  { name: 'African' },
  { name: 'Asian' },
  { name: 'BBQ' },
  { name: 'British' },
  { name: 'Cheese' },
  { name: 'Chinese' },
  { name: 'Curry' },
  { name: 'Ethiopian' },
  { name: 'French' },
  { name: 'German' },
  { name: 'Indian' },
  { name: 'Indonesian' },
  { name: 'Italian' },
  { name: 'Japanese' },
  { name: 'Korean' },
  { name: 'Malaysian' },
  { name: 'Mediterranean' },
  { name: 'Mexican' },
  { name: 'Mezze' },
  { name: 'Middle Eastern' },
  { name: 'Pakistani' },
  { name: 'Pasta' },
  { name: 'Ramen' },
  { name: 'Salad' },
  { name: 'Sandwiches' },
  { name: 'Seafood' },
  { name: 'Steak' },
  { name: 'Sushi' },
  { name: 'Thai' },
  { name: 'Vegetarian' },
  { name: 'Vegan' },
  { name: 'Vietnamese' },
  { name: 'Swiss' },
  { name: 'Burger' },
  { name: 'Chicken' },
  { name: 'Dessert' },
  { name: 'Meat' },
  { name: 'Pizza' },
  { name: 'Rice Dish' },
  { name: 'Soup' },
  { name: 'Burger Shack' },
  { name: 'Chicken Shop' },
  { name: 'Pizzeria' },
  { name: 'Pub' },
  { name: 'Steakhouse' }
];
