name: Node CI

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "dev" ]; then
            echo "Merge requests to main branch are only allowed from dev branch."
            exit 1
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run tests on dev branch'
        run: npm run test:dev
